name: Build Conda packages

on: workflow_dispatch

jobs:
  build-conda:
    name: build-conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          conda-build-version: "*"
      - name: build recipe
        shell: bash -el {0}
        run: conda build -c pytorch -c conda-forge conda-recipe --output-folder dist --python=${{ matrix.python-version }}
      - name: upload builds
        uses: actions/upload-artifact@v3
        with:
          name: conda-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist
          retention-days: 5
          if-no-files-found: error
