name: Build Conda packages

on: [push]

jobs:
  build-conda:
    name: build-conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - python-version: 3.8
            numpy-version: 1.20
          - python-version: 3.9
            numpy-version: 1.20
          - python-version: 3.10
            numpy-version: 1.21
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          conda-build-version: "3.21"
          python-version: ${{ matrix.python-version }}
      - name: build recipe
        shell: bash -el {0}
        run: >
          conda build
            -c conda-forge -c pytorch
            conda-recipe
              --output-folder dist
              --python=${{ matrix.python-version }}
              --numpy=${{ matrix.numpy-version }}
      - name: upload builds
        uses: actions/upload-artifact@v3
        with:
          name: conda-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist
          retention-days: 5
          if-no-files-found: error